spring.application.name=demo
spring.mvc.view.prefix=/WEB-INF/B2B_JSP/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://caboose.proxy.rlwy.net:45506/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=nipeGovGgZOXdgEiYrNJluTreFInFgij
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
